name: package-yml
version: 0.0.1
description: Use YAML for your NPM Package
main: index.js
author: Thomas Reggi
license: MIT
scripts:
  pkgjson: "ruby -ryaml -rjson -e 'puts JSON.pretty_generate(YAML.load(ARGF))' < ./package.yml > ./pkg.json"
dependencies:
  js-yaml: ^3.2.3
